# Version de Python (solo mayor y menor)
ARG PYTHON_VERSION=3.11

# Etapa build
FROM python:${PYTHON_VERSION} AS build

# Se instala uWSGI y todas las librerias que necesita la aplicacion
COPY
RUN
 
# Etapa run
FROM python:${PYTHON_VERSION}-slim AS run

# Es necesario volver a incluir en esta etapa esta variable
ARG PYTHON_VERSION

# Puerto HTTP por defecto para uWSGI
ARG
ENV

# Aplicacion por defecto para uWSGI
ARG
ENV

# Se instalan dependencias
RUN apt-get update && apt-get install -y libxml2

# Se crea un usuario para arrancar uWSGI
RUN useradd
USER

# Se copia el contenido de la imagen builder
COPY --from=build /usr/local/lib/python${PYTHON_VERSION}/site-packages /usr/local/lib/python${PYTHON_VERSION}/site-packages
COPY --from=build /usr/local/bin/uwsgi /usr/local/bin/uwsgi

# Se copia el contenido de la aplicacion
COPY

# Se copia el fichero con la configuración de uWSGI
COPY

# Se establece el directorio de trabajo
WORKDIR

# Se crea un volumen con el contenido de la aplicacion
VOLUME

# Se inicia uWSGI
ENTRYPOINT